<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<PackageTags>Krosoft Extensions Zip Archive</PackageTags>
		<Description>Package pour faciliter l'utilisation d'archives Zip.</Description>
	</PropertyGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Krosoft.Extensions.Core" Version="2026.8.14.9075" />
	</ItemGroup>
</Project>